// Czech translations: the English text is the key (see i18n.ts). A string without an entry stays English.
export const CS: Record<string, string> = {
  // dashboard
  "{name} settings": "Nastavení: {name}",
  "@{who} is offline: gets it when it reconnects": "@{who} je offline: dostane to po připojení",
  "@{who} reads it at its next check-in": "@{who} si to přečte při dalším připojení",
  "a person of {org}": "někdo z {org}",
  "Agents get this contract change once a person of {org} approves it.": "Agenti tuhle změnu kontraktu dostanou, až ji schválí někdo z {org}.",
  "agents have been talking without a person": "agenti spolu mluví bez člověka",
  "Approve": "Schválit",
  "Approved by @{who}": "Schválil @{who}",
  "Ask whoever invited you to give you access to a room.": "Požádej toho, kdo tě pozval, aby ti dal přístup do místnosti.",
  "asks for a destructive command": "chce destruktivní příkaz",
  "asks for secrets": "chce tajné údaje",
  "automatic": "automaticky",
  "Cancel": "Zrušit",
  "Click to let agents' contract changes go out directly": "Klikni, aby se změny kontraktu od agentů odesílaly rovnou",
  "Click to make agents' contract changes wait for a person of their company": "Klikni, aby změny kontraktu od agentů čekaly na člověka z jejich firmy",
  "comes from another company and its recipient holds all of those": "je od jiné firmy a příjemce takové zprávy zadržuje všechny",
  "Connecting to the hub": "Připojuji se k hubu",
  "contains a shell payload": "obsahuje shellový příkaz",
  "contains hidden characters": "obsahuje skryté znaky",
  "Contract change": "Změna kontraktu",
  "Contract changes go out directly": "Změny kontraktu se odesílají rovnou",
  "Contract changes need approval": "Změny kontraktu vyžadují schválení",
  "Delivered to {who}": "Doručeno: {who}",
  "Done": "Hotovo",
  "Edit": "Upravit",
  "Flagged ({why}), delivered: no other company's agent is in this room": "Označeno ({why}), doručeno: v místnosti není agent jiné firmy",
  "From another company, and it {why}. Each owner decides for their own agents.": "Od jiné firmy a {why}. Každý majitel rozhoduje za své agenty.",
  "guest company": "hostující firma",
  "Held for review": "Zadrženo ke kontrole",
  "Held from agents": "Zadrženo před agenty",
  "Hide room context": "Skrýt kontext místnosti",
  "Hub offline": "Hub je offline",
  "in the repo, then reload.": "v repozitáři a pak stránku obnov.",
  "In this room": "V této místnosti",
  "Invite": "Pozvat",
  "Live": "Živě",
  "Loading rooms": "Načítám místnosti",
  "Message {name}": "Zpráva do {name}",
  "Messages are pushed into its running session": "Zprávy se vkládají přímo do jeho běžící session",
  "New room": "Nová místnost",
  "New room inside": "Nová místnost uvnitř",
  "New top-level room": "Nová místnost nejvyšší úrovně",
  "No agent gets this until a person decides: {why}.": "Žádný agent tohle nedostane, dokud se člověk nerozhodne: {why}.",
  "No context yet. Write down what every agent in this room should know first.": "Zatím žádný kontext. Napiš, co by měl každý agent v této místnosti vědět jako první.",
  "No rooms you can see": "Žádné místnosti, které bys viděl",
  "Nobody by that name here.": "Nikdo takový tu není.",
  "Nobody, just looking": "Nikdo, jen se dívám",
  "Note": "Poznámka",
  "Nothing here yet": "Zatím tu nic není",
  "online": "online",
  "Other agents": "Další agenti",
  "Pause": "Pozastavit",
  "Pause {name}": "Pozastavit {name}",
  "paused": "pozastaven",
  "Paused by a person: it can't post and gets no messages": "Pozastavil člověk: nemůže psát a nedostává zprávy",
  "People": "Lidé",
  "Pick yourself under": "Vyber se v poli",
  "Question": "Otázka",
  "Reached over A2A": "Oslovuje se přes A2A",
  "Reads its inbox when it checks in": "Čte svou schránku, když se připojí",
  "Reads this dashboard": "Čte tenhle dashboard",
  "Reject": "Zamítnout",
  "rejected by @{who}: never saw it": "zamítl @{who}: nikdy to neviděl",
  "Rejected by @{who}. No agent ever saw it.": "Zamítl @{who}. Žádný agent to nikdy neviděl.",
  "Release": "Uvolnit",
  "Release to my agents": "Uvolnit mým agentům",
  "released by @{who}": "uvolnil @{who}",
  "Released by @{who}": "Uvolnil @{who}",
  "Resume": "Obnovit",
  "Resume {name}": "Obnovit {name}",
  "Reviewed": "Zkontrolováno",
  "Room context, markdown": "Kontext místnosti, markdown",
  "Room settings": "Nastavení místnosti",
  "Rooms": "Místnosti",
  "Safety log": "Bezpečnostní log",
  "Save context": "Uložit kontext",
  "Secrets masked before anyone saw them ({kinds})": "Tajné údaje zamaskovány dřív, než je kdokoli viděl ({kinds})",
  "Send": "Odeslat",
  "Sending": "Odesílám",
  "Sending to @{who}": "Odesílám @{who}",
  "Settings": "Nastavení",
  "Show room context": "Zobrazit kontext místnosti",
  "Sign out": "Odhlásit se",
  "Start it with": "Spusť ho příkazem",
  "Start your tree": "Založ svůj strom",
  "The hub isn't answering": "Hub neodpovídá",
  "to write in {name}.": "a můžeš psát do {name}.",
  "Today": "Dnes",
  "tries to change the agent's role": "se snaží změnit roli agenta",
  "tries to override the agent's instructions": "se snaží přebít instrukce agenta",
  "wait for {who}": "čekají na: {who}",
  "wait for you": "čekají na tebe",
  "Waiting for approval": "Čeká na schválení",
  "What kind of message": "Druh zprávy",
  "Who is in this room": "Kdo je v této místnosti",
  "Woken in its own thread when mentioned": "Při zmínce se probudí ve svém vlákně",
  "Write to {name}. Type @ to mention someone.": "Napiš do {name}. Zmiň někoho pomocí @.",
  "you": "ty",
  "You are": "Jsi",
  "Add your agent here": "Přidat sem svého agenta",

  // account screens
  "Set up your hub": "Nastav svůj hub",
  "You're the first one here, so you become its owner. You'll invite your team, other companies and their agents next.":
    "Jsi tu první, takže se staneš majitelem. Dál budeš zvát svůj tým, jiné firmy a jejich agenty.",
  "Your name": "Tvoje jméno",
  "Your company": "Tvoje firma",
  "People and agents of other companies show up as guests next to this name.": "Lidé a agenti jiných firem se vedle tohoto jména zobrazí jako hosté.",
  "Email": "E-mail",
  "Password": "Heslo",
  "First room": "První místnost",
  "The top of your tree, usually a product or a client. Leave empty to name it after your company.":
    "Vrchol tvého stromu, obvykle produkt nebo klient. Nech prázdné a pojmenuje se po tvé firmě.",
  "Setup token": "Token pro nastavení",
  "Set in the hub's environment as WARREN_SETUP_TOKEN.": "Nastavuje se v prostředí hubu jako WARREN_SETUP_TOKEN.",
  "Create owner account": "Vytvořit účet majitele",
  "Creating your account": "Vytvářím účet",
  "Sign in": "Přihlásit se",
  "Signing in": "Přihlašuji",
  "Code from your authenticator app": "Kód z autentizační aplikace",
  "Or one of your recovery codes.": "Nebo některý ze záložních kódů.",
  "This invite doesn't work anymore": "Tahle pozvánka už nefunguje",
  "This link doesn't work anymore": "Tenhle odkaz už nefunguje",
  "Opening your invite": "Otevírám pozvánku",
  "Opening your link": "Otevírám odkaz",
  "Join": "Připojit se",
  "Joining": "Připojuji",
  "Set a new password": "Nastav nové heslo",
  "New password": "Nové heslo",
  "Save and sign in": "Uložit a přihlásit",
  "Saving": "Ukládám",
  "At least 10 characters. A few words in a row work well.": "Alespoň 10 znaků. Dobře fungují čtyři slova za sebou.",
  "Forgot your password? Ask an admin of this hub for a reset link.": "Zapomněl jsi heslo? Požádej správce hubu o odkaz pro obnovení.",

  // dialogs
  "Create room": "Vytvořit místnost",
  "Name": "Název",
  "Context": "Kontext",
  "Markdown every agent reads before working here: the contract, decisions, conventions. You can change it later.":
    "Markdown, který každý agent přečte, než tu začne pracovat: kontrakt, rozhodnutí, konvence. Můžeš ho později změnit.",
  "Inside": "Uvnitř",
  "Moving a room changes who sees it: everyone with access to the new parent will, and people who only saw the old one won't.":
    "Přesun místnosti mění, kdo ji vidí: uvidí ji všichni s přístupem k novému rodiči a lidé, kteří viděli jen starého, ji neuvidí.",
  "Parent room": "Nadřazená místnost",
  "Save": "Uložit",
  "Delete room": "Smazat místnost",
  "Delete for good": "Smazat natrvalo",
  "Keep it": "Nechat",
  "Room": "Místnost",
  "Invite a person": "Pozvat člověka",
  "They set their own password from the link, see the room you pick and everything inside it, and can add their own agents there.":
    "Z odkazu si nastaví vlastní heslo, uvidí vybranou místnost a vše uvnitř a mohou tam přidat své agenty.",
  "Company": "Firma",
  "Access": "Přístup",
  "Every room, as an admin": "Všechny místnosti, jako správce",
  "Create invite link": "Vytvořit odkaz s pozvánkou",
  "Invite ready": "Pozvánka je hotová",
  "Invite link": "Odkaz s pozvánkou",
  "Done ": "Hotovo",
  "Add an agent": "Přidat agenta",
  "Add agent": "Přidat agenta",
  "Client": "Klient",
  "What it sees: this room and everything inside it.": "Co vidí: tuto místnost a vše uvnitř.",
  "Its @handle is made from the name.": "Jeho @handle se vytvoří z názvu.",
  "Token": "Token",
  "Add to .mcp.json in your repo": "Přidej do .mcp.json ve svém repozitáři",
  "Then start Claude Code with": "Pak spusť Claude Code příkazem",
  "Connect Codex": "Připoj Codex",
  "Wake it on mentions (bridge, next to Codex)": "Probuzení při zmínce (bridge vedle Codexu)",
  "Wake it on mentions (bridge, next to Cursor)": "Probuzení při zmínce (bridge vedle Cursoru)",
  "Add to .cursor/mcp.json": "Přidej do .cursor/mcp.json",
  "MCP over HTTP": "MCP přes HTTP",
  "A2A agent card": "A2A karta agenta",
  "The token is shown only now. Lost it? Make a new one in Settings; the old one stops working at once.":
    "Token se ukazuje jen teď. Ztratil jsi ho? V Nastavení vytvoř nový, starý přestane okamžitě fungovat.",

  // settings
  "Profile": "Profil",
  "Sign-in": "Přihlášení",
  "Safety": "Bezpečnost",
  "Privacy": "Soukromí",
  "Invites": "Pozvánky",
  "Agents": "Agenti",
  "Hub": "Hub",
  "Owner": "Majitel",
  "Admin": "Správce",
  "Member": "Člen",
  "sees every room": "vidí všechny místnosti",
  "Name saved.": "Jméno uloženo.",
  "Appearance": "Vzhled",
  "Language": "Jazyk",
  "Theme": "Motiv",
  "System": "Systém",
  "Light": "Světlý",
  "Dark": "Tmavý",
  "Password changed. Other sessions were signed out.": "Heslo změněno. Ostatní relace byly odhlášeny.",
  "Current password": "Současné heslo",
  "Change password": "Změnit heslo",
  "Two-factor sign-in": "Dvoufázové přihlášení",
  "Besides your password, sign-in asks for a code from an authenticator app (1Password, Google Authenticator, Aegis…).":
    "Kromě hesla se při přihlášení zadává kód z autentizační aplikace (1Password, Google Authenticator, Aegis…).",
  "Two-factor sign-in is on. Save these recovery codes somewhere safe: each one signs you in once if you lose your phone.":
    "Dvoufázové přihlášení je zapnuté. Ulož si záložní kódy na bezpečné místo: každý tě jednou přihlásí, když ztratíš telefon.",
  "Recovery codes": "Záložní kódy",
  "I saved them": "Uložil jsem je",
  "On.": "Zapnuto.",
  "Code or recovery code": "Kód nebo záložní kód",
  "Turn off": "Vypnout",
  "Turn on": "Zapnout",
  "QR code for your authenticator app": "QR kód pro autentizační aplikaci",
  "Scan the code with your authenticator app, or type in the key.": "Naskenuj kód autentizační aplikací, nebo opiš klíč.",
  "Key": "Klíč",
  "Code from the app": "Kód z aplikace",
  "Set up two-factor sign-in": "Nastavit dvoufázové přihlášení",
  "Two-factor sign-in is off.": "Dvoufázové přihlášení je vypnuté.",
  "Messages to your agents": "Zprávy pro tvé agenty",
  "When someone from another company sends something that looks like an attack (asking for secrets, overriding instructions, shell payloads), Warren holds it. Your agents don't see it until you, their owner, release it.":
    "Když ti někdo z jiné firmy pošle něco, co vypadá jako útok (chce tajné údaje, přebíjí instrukce, shellové příkazy), Warren to zadrží. Tvoji agenti to neuvidí, dokud to ty, jejich majitel, neuvolníš.",
  "Hold every message from another company": "Zadržovat každou zprávu od jiné firmy",
  "Strict mode: even harmless-looking messages from other companies wait for you before your agents get them.":
    "Přísný režim: i nevinně vypadající zprávy od jiných firem čekají na tebe, než je tvoji agenti dostanou.",
  "Email me when a message waits for me": "Poslat e-mail, když na mě čeká zpráva",
  "This hub has no email set up, so you'll only see it in the app.": "Tenhle hub nemá nastavený e-mail, uvidíš to jen v aplikaci.",
  "Approve from your agent's session": "Schvalování z session tvého agenta",
  "Put an approver key next to your agent and Warren asks you right there: Claude Code shows you a dialog your agent can't see, the Codex and Cursor bridge asks in its terminal. The key can only decide for your own agents.":
    "Dej klíč schvalovatele k agentovi a Warren se zeptá přímo tam: Claude Code ti ukáže dialog, který agent nevidí, bridge pro Codex a Cursor se zeptá v terminálu. Klíč může rozhodovat jen za tvé vlastní agenty.",
  "Approver key (shown once)": "Klíč schvalovatele (zobrazí se jednou)",
  "Add it to the bridge's env in .mcp.json": "Přidej ho do env bridge v .mcp.json",
  "The key sits on the same machine as your agent. If your agent runs with unrestricted shell access, it could read it: approve in the app instead.":
    "Klíč leží na stejném stroji jako agent. Pokud agent běží s neomezeným shellem, mohl by si ho přečíst: v takovém případě schvaluj v aplikaci.",
  "Where it will live": "Kde bude ležet",
  "my laptop": "můj notebook",
  "Create key": "Vytvořit klíč",
  "created {date}": "vytvořen {date}",
  "last used {date}": "naposledy použit {date}",
  "Revoke": "Zrušit platnost",
  "Your data": "Tvoje data",
  "This hub stores your name, email, company, password hash, your messages and your agents' messages, and a safety log. It sets one cookie, to keep you signed in.":
    "Tenhle hub ukládá tvoje jméno, e-mail, firmu, otisk hesla, tvoje zprávy a zprávy tvých agentů a bezpečnostní log. Nastavuje jedinou cookie, která tě drží přihlášeného.",
  "Messages are deleted after {days} days.": "Zprávy se mažou po {days} dnech.",
  "Messages are kept until someone deletes them.": "Zprávy se uchovávají, dokud je někdo nesmaže.",
  "Privacy notice": "Zásady ochrany soukromí",
  "Download my data": "Stáhnout moje data",
  "Delete my account": "Smazat můj účet",
  "Your name, email, password and keys are deleted and your agents removed. Your handle stays reserved so old threads still read, signed “Former member”.":
    "Tvoje jméno, e-mail, heslo a klíče se smažou a tvoji agenti odstraní. Handle zůstane rezervovaný, aby starší vlákna dávala smysl, podepsaná „Former member“.",
  "You own this hub. Hand over ownership in People first.": "Tenhle hub vlastníš. Nejdřív předej vlastnictví v sekci Lidé.",
  "Also delete everything I and my agents wrote": "Smazat i všechno, co jsem já a moji agenti napsali",
  "Pending invites": "Čekající pozvánky",
  "Invites you sent": "Pozvánky, které jsi poslal",
  "No open invites. Links you create show up here until someone uses them.": "Žádné otevřené pozvánky. Odkazy, které vytvoříš, tu zůstanou, dokud je někdo nepoužije.",
  "no email": "bez e-mailu",
  "2FA": "2FA",
  "Role of {name}": "Role: {name}",
  "What {name} sees": "Co vidí {name}",
  "Sees {where}": "Vidí: {where}",
  "Password reset link": "Odkaz pro reset hesla",
  "Remove {name} and their agents": "Odebrat {name} a jeho agenty",
  "Keep": "Nechat",
  "Remove": "Odebrat",
  "Emailed to {email}; valid for a day": "Odesláno na {email}; platí den",
  "Send this to them; it works once, for a day": "Pošli jim to; funguje jednou a den",
  "Anyone with the link": "Kdokoli s odkazem",
  "admin, every room": "správce, všechny místnosti",
  "by": "od",
  "until {date}": "do {date}",
  "Your agents": "Tvoji agenti",
  "Each agent gets its own token and sees one room and the rooms inside it. It belongs to you and your company; you pause it, and you approve what other companies send it.":
    "Každý agent má vlastní token a vidí jednu místnost a místnosti v ní. Patří tobě a tvé firmě; ty ho pozastavuješ a schvaluješ, co mu posílají jiné firmy.",
  "No agents yet. Add one and paste its setup into Claude Code, Codex or Cursor.": "Zatím žádní agenti. Přidej jednoho a vlož jeho nastavení do Claude Code, Codexu nebo Cursoru.",
  "pushed into its session": "vkládá se přímo do session",
  "woken on mention": "probouzí se při zmínce",
  "reads its inbox": "čte svou schránku",
  "dashboard": "dashboard",
  "nobody": "nikdo",
  "owner {name}": "majitel {name}",
  "offline": "offline",
  "Replace token": "Vyměnit token",
  "The running agent loses access until you paste the new one.": "Běžící agent ztratí přístup, dokud nevložíš nový.",
  "Remove @{handle}": "Odebrat @{handle}",
  "New token": "Nový token",
  "This hub": "Tenhle hub",
  "You run this hub, so you decide how long it keeps messages and who people contact about their data.":
    "Tenhle hub provozuješ ty, takže rozhoduješ, jak dlouho uchovává zprávy a koho mají lidé kontaktovat kvůli svým datům.",
  "Delete messages after (days)": "Mazat zprávy po (dnech)",
  "Empty or 0 keeps them. Older messages are deleted every hour; the safety log stays.": "Prázdné nebo 0 je nechá. Starší zprávy se mažou každou hodinu; bezpečnostní log zůstává.",
  "Privacy contact": "Kontakt pro soukromí",
  "Shown in the privacy notice: who people write to about their data (an email or a web page).":
    "Zobrazí se v zásadách ochrany soukromí: komu lidé píšou ohledně svých dat (e-mail nebo web).",
  "Saved.": "Uloženo.",
};
